#include <stdio.h>

int main() {
    int errors = 0, checkpoints = 0;

    __asm__ volatile(
    "li t1, 0x0\n\t"    // error count
    "li t2, 0x0\n\t"    // checkpoint instructions that should be run
"test1:\n\t"
    "li t3, 0x00000005\n\t"
    "cv.beqimm t3, 0x05, check1\n\t"
    "c.addi t1, 0x1\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
"check1:\n\t"
    "c.addi t2, 0x1\n\t"
"test2:\n\t"
    "li t3, -10\n\t"
    "cv.beqimm t3, -10, check2\n\t"
    "c.addi t1, 0x1\n\t"
    "nop\n\t"
    "nop\n\t"
"check2:\n\t"
    "c.addi t2, 0x1\n\t"
"test3:\n\t"
    "li t3, -3\n\t"
    "cv.beqimm t3, -3, check3\n\t"
    "c.addi t1, 0x1\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
"check3:\n\t"
    "c.addi t2, 0x1\n\t"
"test4:\n\t"
    "li t3, 0x00000007\n\t"
    "cv.beqimm t3, 0x07, check4\n\t"
    "c.addi t1, 0x1\n\t"
"check4:\n\t"
    "c.addi t2, 0x1\n\t"
"test5:\n\t"
    "li t3, 0x00000000\n\t"
    "cv.beqimm t3, 0x01, exit_check\n\t"
    "c.addi t2, 0x1\n\t"
"test6:\n\t"
    "li t3, -7\n\t"
    "cv.beqimm t3, -6, exit_check\n\t"
    "c.addi t2, 0x1\n\t"
"test7: #114\n\t"
    "li t3, 0xffffffff\n\t"
    "cv.bneimm t3, 0xe, check7\n\t"
    "c.addi t1, 0x1\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
"check7:\n\t"
    "c.addi t2, 0x1\n\t"
"test8:\n\t"
    "li t3, -10\n\t"
    "cv.bneimm t3, -8, check8\n\t"
    "c.addi t1, 0x1\n\t"
    "nop\n\t"
    "nop\n\t"
"check8:\n\t"
    "c.addi t2, 0x1\n\t"
"test9:\n\t"
    "li t3, -3\n\t"
    "cv.bneimm t3, 5, check9\n\t"
    "c.addi t1, 0x1\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
    "nop\n\t"
"check9:\n\t"
    "c.addi t2, 0x1\n\t"
"test10:\n\t"
    "li t3, 0x00000008\n\t"
    "cv.bneimm t3, 0x06, check10\n\t"
    "c.addi t1, 0x1\n\t"
"check10:\n\t"
    "c.addi t2, 0x1\n\t"
"test11:\n\t"
    "li t3, 0x00000000\n\t"
    "cv.bneimm t3, 0x00, exit_check\n\t"
    "c.addi t2, 0x1\n\t"
"test12:\n\t"
    "li t3, -7\n\t"
    "cv.bneimm t3, -7, exit_check\n\t"
    "c.addi t2, 0x1\n\t"
"exit_check:\n\t"
    "mv %0, t1\n\t"
    "mv %1, t2\n\t"
    : "=r" (errors), "=r" (checkpoints)
    :
    : "t1", "t2", "t3"
    );

    printf("errors = %d\n", errors);
    printf("checkpoints = %d of 12\n", checkpoints);
    return 0;
}
